# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ysr < Formula
  desc "A tool to manage template files with external stores."
  homepage "https://github.com/dwango/yashiro"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/dwango/yashiro/releases/download/v0.4.0/ysr-darwin-amd64.tar.gz"
      sha256 "55951584b391fe7b72be918caf5dc6244fdb4efd1efd34ee6a85f5de20d60788"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
    on_arm do
      url "https://github.com/dwango/yashiro/releases/download/v0.4.0/ysr-darwin-arm64.tar.gz"
      sha256 "a84f5f681ddffac62825e7c432b949f4eb442e60d6d0871e98047f63acc8d82e"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.4.0/ysr-linux-amd64.tar.gz"
        sha256 "3b95b80b723fab878f0a2f06dc91f2e26905b7ffd64553ddf7fc9fa27a33736d"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.4.0/ysr-linux-arm64.tar.gz"
        sha256 "b121300d5f329b5a5db69b64c213ff533c140af85415ebd44511ac47682daf77"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/ysr version")
    assert_match "0.4.0", version_output
  end
end
