# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ysr < Formula
  desc "A tool to manage template files with external stores."
  homepage "https://github.com/dwango/yashiro"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/dwango/yashiro/releases/download/v0.3.0/ysr-darwin-amd64.tar.gz"
      sha256 "761c175ac2561cfb900871211119f305543f02c61440ec8dbf39fac2b9783c89"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
    on_arm do
      url "https://github.com/dwango/yashiro/releases/download/v0.3.0/ysr-darwin-arm64.tar.gz"
      sha256 "4017bfd2667471d194e964842303e26c8a0ed831a8d55a7a1da9c6ffb4505930"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.3.0/ysr-linux-amd64.tar.gz"
        sha256 "181217339a930f00b415036d82df305e10135ec24b202fe57d2d581d3b6fa2a9"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.3.0/ysr-linux-arm64.tar.gz"
        sha256 "3e2b828d8ebc610abdc8ed64cc2f54abd1a820b74d92f0f6816ed7ed8367c769"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/ysr version")
    assert_match "0.3.0", version_output
  end
end
