# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ysr < Formula
  desc "A tool to manage template files with external stores."
  homepage "https://github.com/dwango/yashiro"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/dwango/yashiro/releases/download/v0.5.0/ysr-darwin-amd64.tar.gz"
      sha256 "242aa31cf9b6f893061d5d9d3f57db24b9af7f03619043b66a0efb79b8144aee"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
    on_arm do
      url "https://github.com/dwango/yashiro/releases/download/v0.5.0/ysr-darwin-arm64.tar.gz"
      sha256 "0facc9ab0423149a5e56eb8a975e92ebd5dbb6f832581ec79578d8783b9a0293"

      def install
        bin.install "ysr"
        generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.5.0/ysr-linux-amd64.tar.gz"
        sha256 "14bb0f0dd0d8328f7da6aefa3b8af0170267a983d03e821fb8898e3c25e08a21"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dwango/yashiro/releases/download/v0.5.0/ysr-linux-arm64.tar.gz"
        sha256 "25c126cc3a41e924c77599cdda345fdb42a05adc756270d945fedfef48e508f1"

        def install
          bin.install "ysr"
          generate_completions_from_executable(bin/"ysr", "completion", base_name: "ysr")
        end
      end
    end
  end

  test do
    version_output = shell_output("#{bin}/ysr version")
    assert_match "0.5.0", version_output
  end
end
